from mimesis import Text, Address
from playwright.sync_api import Page, expect
from ..conftest import BASE_URL

text = Text('en')
address = Address('en')

def test_create_journey_for_edit_log(page: Page):
    page.goto("https://comp639prj2rar.pythonanywhere.com/home")
    expect(page.get_by_role("link", name="Get Started")).to_be_visible()
    page.get_by_role("link", name="Get Started").click()
    # Login as free user
    page.get_by_role("textbox", name=" Username").click()
    page.get_by_role("textbox", name=" Username").fill("traveller3")
    page.get_by_role("textbox", name=" Password").click()
    page.get_by_role("textbox", name=" Password").fill("1qaz@WSX")
    page.get_by_role("button", name="Log In").click()
    # Create a journey for free user
    page.get_by_role("link", name=" My Journey").click()
    edit_link = page.get_by_role("link", name="Edit log for free user Edit")
    if edit_link.count() > 0:
        edit_link.click()
        page.get_by_role("button", name=" Delete Journey").click()
        page.get_by_role("button", name="Delete", exact=True).click()

    page.get_by_role("link", name=" Journey").click()
    page.get_by_role("textbox", name="Title *").click()
    page.get_by_role("textbox", name="Title *").fill("Edit log for free user")
    page.get_by_role("textbox", name=" Start Date *").fill("2025-06-10")
    page.get_by_role("textbox", name=" Description *").click()
    page.get_by_role("textbox", name=" Description *").fill("Edit log for free user")
    page.get_by_label("Sharing *").select_option("public")
    page.get_by_role("button", name=" Add Journey").click()
    # Create a event for free user
    page.get_by_role("link", name=" My Journey").click()
    page.get_by_role("link", name="Edit log for free user Edit").click()
    page.get_by_role("link", name=" Add Event").click()
    page.get_by_role("textbox", name="Title *").click()
    page.get_by_role("textbox", name="Title *").fill("Edit log for free user")
    page.get_by_role("textbox", name="Start Date *").fill("2025-06-10")
    page.get_by_role("textbox", name="Start Time *").click()
    page.get_by_role("textbox", name="Start Time *").press("ArrowUp")
    page.get_by_role("textbox", name="Start Time *").press("ArrowRight")
    page.get_by_role("textbox", name="Start Time *").press("ArrowUp")
    page.get_by_role("textbox", name="Start Time *").press("ArrowRight")
    page.get_by_role("textbox", name="Start Time *").press("ArrowUp")
    page.locator("#location_id").select_option("7")
    page.get_by_role("button", name=" Add Event").click()
    # Log out free user
    page.get_by_role("link", name=" Traveller3 Free").click()
    page.wait_for_timeout(1000)
    page.get_by_role("link", name=" Sign out").click()
    page.get_by_role("link", name="Get Started").click()
    # Login as premium user
    page.get_by_role("textbox", name=" Username").click()
    page.get_by_role("textbox", name=" Username").fill("traveller13")
    page.get_by_role("textbox", name=" Password").click()
    page.get_by_role("textbox", name=" Password").fill("1qaz@WSX")
    page.get_by_role("button", name="Log In").click()
    # Create a journey for premium user
    page.get_by_role("link", name=" My Journey").click()
    edit_link = page.get_by_role("link", name="Edit log for premium user")
    if edit_link.count() > 0:
        edit_link.click()
        page.get_by_role("button", name=" Delete Journey").click()
        page.get_by_role("button", name="Delete", exact=True).click()
    page.get_by_role("link", name=" Journey").click()
    page.get_by_role("textbox", name="Title *").click()
    page.get_by_role("textbox", name="Title *").fill("Edit log for premium user")
    page.get_by_role("textbox", name=" Description *").click()
    page.get_by_role("textbox", name=" Description *").fill("Edit log for premium user")
    page.get_by_label("Sharing *").select_option("public")
    page.get_by_role("button", name=" Add Journey").click()
    # Upload a cover image for premium user
    page.get_by_role("link", name="Edit log for premium user").click()
    page.get_by_role("button", name=" Edit Journey").click()
    page.wait_for_timeout(1000)
    with page.expect_file_chooser() as fc_info:
        page.get_by_role("button", name=" Add Cover").click()
    file_chooser = fc_info.value
    file_chooser.set_files("../COMP639_Project_2_RAR/test/data/image/Camping.jpg")
    # page.get_by_role("button", name=" Add Cover").click()
    # page.locator('input[type="file"]').set_input_files("C:\\Users\\admin\\Desktop\\Camping.jpg")
    page.get_by_role("button", name=" Save Changes").click()
    # NO EDIT - Create a journey for premium user
    page.get_by_role("link", name=" My Journey").click()
    edit_link = page.get_by_role("link", name="No Edit for premium user")
    if edit_link.count() > 0:
        edit_link.click()
        page.get_by_role("button", name=" Delete Journey").click()
        page.get_by_role("button", name="Delete", exact=True).click()
    page.get_by_role("link", name=" Journey").click()
    page.get_by_role("textbox", name="Title *").click()
    page.get_by_role("textbox", name="Title *").fill("No Edit for premium user")
    page.get_by_role("textbox", name=" Description *").click()
    page.get_by_role("textbox", name=" Description *").fill("No Edit for premium user")
    page.get_by_label("Sharing *").select_option("public")
    page.get_by_role("button", name=" Add Journey").click()

    page.pause()

def test_edit_log_staff(page: Page):
    page.goto(BASE_URL)
    expect(page.get_by_role("link", name="Get Started")).to_be_visible()
    page.wait_for_timeout(2000)
    page.get_by_role("link", name="Get Started").click()
    page.get_by_role("textbox", name=" Username").click()
    page.get_by_role("textbox", name=" Username").fill("admin3")
    page.get_by_role("textbox", name=" Password").click()
    page.get_by_role("textbox", name=" Password").fill("1qaz@WSX")
    page.get_by_role("button", name="Log In").click()
    expect(page.get_by_role("heading", name="Welcome, Admin3  Admin")).to_be_visible()
    page.get_by_role("link", name=" Public Journey").click()
    expect(page.get_by_role("heading", name="Search")).to_be_visible()
    page.locator("#searchJourneyBy").select_option("1")
    page.get_by_role("textbox", name="Search by Title or").click()
    page.get_by_role("textbox", name="Search by Title or").fill("edit log")
    page.get_by_role("button", name=" Search").click()
    page.get_by_role("link", name="Edit Log for premium user").click()
    expect(page.get_by_text("Journey Details Creator:")).to_be_visible()
    page.locator("#editButton").click()
    page.get_by_role("textbox", name="Description").click()
    page.get_by_role("textbox", name="Description").fill("Edit Log for premium user " + text.word())
    page.get_by_role("button", name="", exact=True).click()
    page.get_by_role("textbox", name=" Staff Reason for").click()
    page.get_by_role("textbox", name=" Staff Reason for").fill("Modified description and remove cover!")
    page.get_by_role("button", name=" Save Changes").click()
    page.get_by_role("link", name=" Public Journey").click()
    page.locator("#searchJourneyBy").select_option("1")
    page.get_by_role("textbox", name="Search by Title or").click()
    page.get_by_role("textbox", name="Search by Title or").fill("edit log")
    page.get_by_role("button", name=" Search").click()
    page.get_by_role("link", name="Edit Log for free user Edit").click()
    expect(page.get_by_text("Journey Details Creator:")).to_be_visible()
    page.get_by_role("link", name=" View").click()
    expect(page.get_by_text("Edit log for free user").first).to_be_visible()
    page.get_by_role("link", name=" Edit").click()
    page.get_by_role("textbox", name="Or enter a new location").click()
    page.get_by_role("textbox", name="Or enter a new location").fill(address.city())
    page.get_by_role("textbox", name=" Staff Reason for").click()
    page.get_by_role("textbox", name=" Staff Reason for").fill("Modified location")
    page.get_by_role("button", name=" Save Changes").click()

    page.pause()

def test_create_appeal(page: Page):
    page.goto("https://comp639prj2rar.pythonanywhere.com/home")
    expect(page.get_by_role("link", name="Get Started")).to_be_visible()
    page.get_by_role("link", name="Get Started").click()
    page.get_by_role("textbox", name=" Username").click()
    page.get_by_role("textbox", name=" Username").fill("traveller13")
    page.get_by_role("textbox", name=" Password").click()
    page.get_by_role("textbox", name=" Password").fill("1qaz@WSX")
    page.get_by_role("button", name="Log In").click()
    page.get_by_role("link", name=" My Journey").click()
    page.get_by_role("link", name="No Edit for premium user No").click()
    page.wait_for_timeout(5000)
    expect(page.get_by_role("link", name=" Appeal")).to_be_visible()
    page.get_by_role("link", name=" Appeal").click()
    page.get_by_role("textbox", name="Appeal Summary *").click()
    page.get_by_role("textbox", name="Appeal Summary *").fill("Unhidden please!")
    page.get_by_role("textbox", name=" Detailed Explanation *").click()
    page.get_by_role("textbox", name=" Detailed Explanation *").fill("Unhidden please!")
    page.get_by_role("button", name=" Submit Appeal").click()
    page.get_by_role("button", name=" Close").click()
    page.get_by_role("link", name=" Traveller13 Free").click()
    page.get_by_role("link", name=" Sign out").click()
    expect(page.get_by_role("link", name="Get Started")).to_be_visible()
    page.get_by_role("link", name="Get Started").click()
    page.wait_for_timeout(5000)
    page.get_by_role("textbox", name=" Username").click()
    page.get_by_role("textbox", name=" Username").fill("traveller18")
    page.get_by_role("textbox", name=" Password").click()
    page.get_by_role("textbox", name=" Password").fill("1qaz@WSX")
    page.get_by_role("button", name="Log In").click()
    page.get_by_role("link", name=" My Journey").click()
    page.wait_for_timeout(5000)
    page.get_by_role("link", name=" Appeal").click()
    page.get_by_role("textbox", name="Appeal Summary *").click()
    page.get_by_role("textbox", name="Appeal Summary *").click()
    page.get_by_role("textbox", name="Appeal Summary *").fill("Please restore my sharing permissions")
    page.get_by_role("textbox", name=" Detailed Explanation *").click()
    page.get_by_role("textbox", name=" Detailed Explanation *").fill("Please restore my sharing permissions")
    page.get_by_role("button", name=" Submit Appeal").click()
    page.get_by_role("button", name=" Close").click()
    page.get_by_role("link", name=" Traveller18 Trial").click()
    page.get_by_role("link", name=" Sign out").click()
    expect(page.get_by_role("link", name="Get Started")).to_be_visible()
    page.get_by_role("link", name="Get Started").click()
    page.wait_for_timeout(5000)
    page.get_by_role("textbox", name=" Username").click()
    page.get_by_role("textbox", name=" Username").fill("traveller8")
    page.get_by_role("textbox", name=" Password").click()
    page.get_by_role("textbox", name=" Password").fill("1qaz@WSX")
    page.get_by_role("button", name="Log In").click()
    expect(page.get_by_role("heading", name="Access Denied")).to_be_visible()
    page.wait_for_timeout(5000)
    page.get_by_role("link", name=" submit a ban appeal").click()
    page.get_by_role("textbox", name="Appeal Summary *").click()
    page.get_by_role("textbox", name="Appeal Summary *").fill("Please reactivate my login access")
    page.get_by_role("textbox", name=" Detailed Explanation *").click()
    page.get_by_role("textbox", name=" Detailed Explanation *").fill("Please reactivate my login access")
    page.get_by_role("button", name=" Submit Appeal").click()

    page.pause()