import time
from mimesis import Person
from playwright.sync_api import Page, expect
from ..conftest import BASE_URL, APP_REGISTRATION_URL

def test_traveller_4(page: Page, fake_data: Person):
    '''Traveller4 activities to create a request and make a comment'''
    page.goto(BASE_URL)
    page.get_by_role("link", name="Get Started").click()
    page.get_by_role("textbox", name=" Username").fill("Traveller4")
    page.get_by_role("textbox", name=" Password").fill("1qaz@WSX")
    page.wait_for_timeout(1000) 
    page.get_by_role("button", name="Log In").click()
    expect(page.get_by_text("Traveller", exact=True)).to_be_visible()
    page.get_by_role("link", name=" Helpdesk").click()
    page.wait_for_timeout(4000) 
    page.get_by_role("link", name=" New Support Request").click()
    expect(page.get_by_role("heading", name="Create Support Request")).to_be_visible()
    page.wait_for_timeout(2000) 
    page.get_by_role("button", name="Submit Request").click()
    expect(page.get_by_text("Please select an issue type")).to_be_visible()
    expect(page.get_by_text("Summary is required")).to_be_visible()
    expect(page.get_by_text("Description is required")).to_be_visible()
    page.wait_for_timeout(4000) 
    page.get_by_label("Issue Type *").select_option("Others")
    page.get_by_role("textbox", name="Summary *").fill("Colour suggestion")
    page.get_by_role("textbox", name=" Description *").fill("I like grey background instead of white")
    page.wait_for_timeout(2000) 
    with page.expect_file_chooser() as fc_info:
        page.get_by_role("button", name="Screenshot (Optional)").click()
        page.wait_for_timeout(1000) 
        file_chooser = fc_info.value
        file_chooser.set_files("../COMP639_Project_2_RAR/test/data/image/grey.png")
        # file_chooser.set_files("C:\\Users\\Doraemon_NB\\Desktop\\Heng\\Lincoln\\COMP639 Studio Project\\Last Assignment\\COMP639_Project_2_RAR\\test\\data\\image\\grey.png")
    page.wait_for_timeout(1000) 
    page.get_by_role("button", name="Submit Request").click()
    expect(page.get_by_text("Your support request has been")).to_be_visible()
    page.wait_for_timeout(10000) 
    page.get_by_role("button", name=" Send Comment").click()
    page.wait_for_timeout(2000) 
    page.get_by_role("textbox", name="Add Comment").click()
    page.get_by_role("textbox", name="Add Comment").fill("   ")
    page.wait_for_timeout(2000) 
    page.get_by_role("button", name=" Send Comment").click()
    expect(page.get_by_text("Comment cannot be empty.")).to_be_visible()
    page.wait_for_timeout(2000) 
    page.get_by_role("textbox", name="Add Comment").click()
    page.get_by_role("textbox", name="Add Comment").fill("This is my suggestion only.")
    page.wait_for_timeout(2000) 
    page.get_by_role("button", name=" Send Comment").click()
    expect(page.get_by_text("Comment added successfully.")).to_be_visible()
    page.wait_for_timeout(1000) 
    page.get_by_role("link", name=" Back to List").click()
    page.wait_for_timeout(3000) 
    page.click('div[class="user-section p-3"] a[data-bs-toggle="dropdown"]')
    page.wait_for_timeout(1000) 
    page.get_by_role("link", name=" Sign out").click()