import time
from mimesis import Person
from playwright.sync_api import Page, expect
from ..conftest import BASE_URL, APP_REGISTRATION_URL

def test_editor_4(page: Page, fake_data: Person):
    page.goto(BASE_URL)
    '''Editor4 activities to reply a comment, take request, drop request, assign request to other staff and update request status'''
    page.get_by_role("link", name="Get Started").click()
    page.get_by_role("textbox", name=" Username").fill("editor4")
    page.get_by_role("textbox", name=" Password").fill("1qaz@WSX")
    page.wait_for_timeout(1000) 
    page.get_by_role("button", name="Log In").click()
    expect(page.get_by_text("Editor", exact=True)).to_be_visible()
    page.wait_for_timeout(1000) 
    page.get_by_role("link", name=" Helpdesk").click()
    page.wait_for_timeout(10000) 
    page.get_by_role("row", name="Please restore my sh...").get_by_role("link").click()
    page.wait_for_timeout(5000)
    expect(page.get_by_role("heading", name="Please restore my sharing")).to_be_visible()
    page.get_by_role("button", name=" Take Responsibility").click()
    page.wait_for_timeout(4000) 
    expect(page.get_by_text("You've successfully taken")).to_be_visible()
    page.wait_for_timeout(1000) 
    page.get_by_label("Status").select_option("Open")
    page.wait_for_timeout(3000) 
    page.get_by_role("button", name=" Update Status").click()
    page.wait_for_timeout(3000) 
    expect(page.get_by_text("Request status updated")).to_be_visible()
    page.wait_for_timeout(2000) 
    page.get_by_role("textbox", name="Add Comment").click()
    page.wait_for_timeout(1000) 
    page.get_by_role("textbox", name="Add Comment").fill("I will report to Support tech for review. Thank you for your suggestion.")
    page.wait_for_timeout(2000) 
    page.get_by_role("button", name=" Send Comment").click()
    page.wait_for_timeout(1000) 
    page.get_by_label("Status").select_option("Stalled")
    page.wait_for_timeout(4000) 
    page.get_by_role("button", name=" Update Status").click()
    page.wait_for_timeout(2000) 
    page.get_by_role("button", name=" Drop Request").click()
    page.wait_for_timeout(4000) 
    expect(page.get_by_text("You've successfully")).to_be_visible()
    page.wait_for_timeout(1000) 
    page.get_by_label("Assign To").select_option("34")
    page.wait_for_timeout(4000) 
    page.get_by_role("button", name=" Confirm").click()
    expect(page.get_by_text("Request has been successfully")).to_be_visible()
    page.wait_for_timeout(1000) 
    page.click('div[class="user-section p-3"] a[data-bs-toggle="dropdown"]')
    page.wait_for_timeout(1000) 
    page.get_by_role("link", name=" Sign out").click()





def test_supporttech_intro(page: Page, fake_data: Person):
    page.goto(BASE_URL)

    '''Introduction of Support Tech and resolve a request of restricted-sharing status'''
    page.get_by_role("link", name="Get Started").click()   
    page.get_by_role("textbox", name=" Username").fill("supporttech4")
    page.get_by_role("textbox", name=" Password").fill("1qaz@WSX")
    page.wait_for_timeout(1000) 
    page.get_by_role("button", name="Log In").click()
    expect(page.get_by_text("Support_tech")).to_be_visible()
    page.wait_for_timeout(1000) 
    page.get_by_role("link", name=" Helpdesk").click()
    page.wait_for_timeout(1000) 
    page.get_by_role("row", name="Please restore my sh...").get_by_role("link").click()
    page.wait_for_timeout(1000)
    expect(page.get_by_role("heading", name="Please restore my sharing")).to_be_visible()
    page.wait_for_timeout(3000) 
    page.get_by_label("Status").select_option("Open")
    page.wait_for_timeout(2000) 
    page.get_by_role("button", name=" Update Status").click()
    page.wait_for_timeout(4000) 
    expect(page.get_by_text("Request status updated")).to_be_visible()
    page.wait_for_timeout(3000) 
    page.get_by_role("link", name=" Manage Users").click()
    page.wait_for_timeout(6000) 
    page.get_by_role("textbox", name="Search by username, first/").click()
    page.wait_for_timeout(1000) 
    page.get_by_role("textbox", name="Search by username, first/").fill("18")
    page.wait_for_timeout(2000) 
    page.get_by_role("button", name="").click()
    page.wait_for_timeout(2000)
    expect(page.get_by_role("cell", name="Traveller18").first).to_be_visible()
    
    # Accept the confirmation dialog when triggered
    page.once("dialog", lambda dialog: dialog.accept())

    # Select the 'active' option to trigger the dialog
    status_dropdown = page.locator('select[name="status"]')
    page.wait_for_timeout(1000) 
    status_dropdown.wait_for(state='visible')
    status_dropdown.select_option("active")
    page.wait_for_timeout(1000) 

    # Wait for the flash message after confirming the dialog
    expect(page.get_by_text("The user's status has been", exact=False)).to_be_visible()
    page.wait_for_timeout(1000) 
    page.get_by_role("link", name=" Helpdesk").click()
    page.wait_for_timeout(1000) 
    page.get_by_role("row", name="1 Please restore my sh...").get_by_role("link").click()
    page.get_by_role("textbox", name="Add Comment").click()
    page.wait_for_timeout(2000) 
    page.get_by_role("textbox", name="Add Comment").fill("I have restore your account status. Sorry for any inconvenience made.")
    page.wait_for_timeout(2000) 
    page.get_by_role("button", name=" Send Comment").click()
    page.wait_for_timeout(1000) 
    expect(page.get_by_text("Comment added successfully.")).to_be_visible()
    page.wait_for_timeout(1000) 
    page.get_by_label("Status").select_option("Resolved")
    page.wait_for_timeout(2000) 
    page.get_by_role("button", name=" Update Status").click()
    page.wait_for_timeout(4000) 
    expect(page.get_by_text("Request status updated")).to_be_visible()
    page.wait_for_timeout(1000) 
    page.get_by_role("link", name=" Back to List").click()
    page.wait_for_timeout(3000) 
    page.get_by_role("link", name="2").click()
    page.wait_for_timeout(3000) 
    page.locator("#statusDropdown").click()
    page.wait_for_timeout(2000) 
    page.get_by_role("link", name="Resolved").click()
    page.wait_for_timeout(3000) 
    page.click('div[class="user-section p-3"] a[data-bs-toggle="dropdown"]')
    page.wait_for_timeout(1000) 
    page.get_by_role("link", name=" Sign out").click()


    '''Test Gift subscription functionality by support tech'''
    # page.get_by_role("link", name=" Manage Users").click()
    # expect(page.get_by_role("heading", name="All Users")).to_be_visible()
    # page.wait_for_timeout(10000) 
    # page.locator("select[name=\"filter\"]").select_option("Premium")
    # page.wait_for_timeout(1000) 
    # page.get_by_role("button", name="").click()
    # page.wait_for_timeout(1000) 
    # page.get_by_role("row", name=" Traveller14 Evelyn Price").get_by_role("link").click()
    # expect(page.get_by_role("heading", name="Traveller14")).to_be_visible()
    # page.wait_for_timeout(1000) 
    # page.get_by_role("link", name="Gift Subscription").click()
    # page.get_by_label("Select Subscription Duration:").select_option("5")
    # page.wait_for_timeout(1000) 
    # page.get_by_label("Reason for Gift:").select_option("High-quality content")
    # page.wait_for_timeout(1000) 
    # page.get_by_role("button", name="Confirm Gift").click()
    # expect(page.get_by_text("Successfully gifted 1 month(s")).to_be_visible()
    # page.wait_for_timeout(1000) 
    # page.get_by_role("link", name="Subscription History").click()
    # page.wait_for_timeout(1000) 
    # page.click('div[class="user-section p-3"] a[data-bs-toggle="dropdown"]')
    # page.wait_for_timeout(1000) 
    # page.get_by_role("link", name=" Sign out").click()


'''Support Tech 4 activities to deal with request, comment and update request status '''
# def test_supporttech_4(page: Page, fake_data: Person): 
#     page.goto(BASE_URL)
#     page.get_by_role("link", name="Get Started").click()
#     page.get_by_role("textbox", name=" Username").fill("supporttech4")
#     page.get_by_role("textbox", name=" Password").fill("1qaz@WSX")
#     page.wait_for_timeout(1000) 
#     page.get_by_role("button", name="Log In").click()
#     expect(page.get_by_text("Support_tech")).to_be_visible()
#     page.wait_for_timeout(1000) 
#     page.get_by_role("link", name=" Helpdesk").click()
#     page.wait_for_timeout(1000) 
#     page.get_by_role("row", name="Colour suggestion Others").get_by_role("link").click()
#     page.wait_for_timeout(4000) 
#     page.get_by_role("button", name=" Take Responsibility").click()
#     page.wait_for_timeout(1000) 
#     expect(page.get_by_text("You've successfully taken")).to_be_visible()
#     page.wait_for_timeout(1000) 
#     page.get_by_label("Status").select_option("Open")
#     page.wait_for_timeout(1000) 
#     page.get_by_role("button", name=" Update Status").click()
#     expect(page.get_by_text("Request status updated")).to_be_visible()
#     page.wait_for_timeout(3000) 
#     page.get_by_role("textbox", name="Add Comment").click()
#     page.get_by_role("textbox", name="Add Comment").fill("This is a new feature that will be available very soon. Thank you for your patience.")
#     page.wait_for_timeout(3000) 
#     page.get_by_role("button", name=" Send Comment").click()
#     expect(page.get_by_text("Comment added successfully.")).to_be_visible()
#     page.wait_for_timeout(3000) 
#     page.get_by_label("Status").select_option("Resolved")
#     page.wait_for_timeout(1000) 
#     page.get_by_role("button", name=" Update Status").click()
#     expect(page.get_by_text("Request status updated")).to_be_visible()
#     page.wait_for_timeout(3000) 
#     page.get_by_role("link", name=" Back to List").click()
#     page.wait_for_timeout(2000) 
#     page.click('div[class="user-section p-3"] a[data-bs-toggle="dropdown"]')
#     page.wait_for_timeout(5000) 
#     page.get_by_role("link", name=" Sign out").click()
